config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(10) } 
end

app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase}
    has_many :messages, dependent: :destroy
    validates :username, presence: true,
                         uniqueness: { case_sensitive: false },
                         length: {minimum: 3, maximum: 15}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: {maximum: 105},
                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_cache_headers
    helper_method :current_user, :logged_in?


    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

    private
    def set_cache_headers
        response.headers["Cache-Control"] = "no-cache, no-store"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "Mon, 01 Jan 1990 00:00:00 GMT"
      end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    before_action :require_user

def index
    @message = Message.new
    @messages = Message.custom_display
end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel",
                                        mod_message: message_render(message)
        end
    end

    private
     def message_params
        params.require(:message).permit(:body)
     end

     def message_render(message)
        render(partial: 'message', locals: {message: message})
     end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "Welcome to MessageMe app"
        redirect_to root_path
    else
       flash.now[:error] = "There was something wrong with your login details"
       render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:info] = "You logged out successfully"
    redirect_to login_path
  end


  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
      @user = User.new
  end
  def create
      @user = User.new(user_params)
      if @user.save
          session[:user_id] = @user.id
          flash[:success] = "Welcome to MessageMe app #{@user.username}, you have successfully signed up"
          redirect_to root_path
      else
          render 'new'
      end
  end
  def edit
  end
  def update
      if @user.update(user_params)
          redirect_to user_path(@user), success: "User profile  updated successfully."

      else
          render 'edit'
      end
  end
  
  
  def destroy
      @user.destroy
      session[:user_id] = nil if @user ==  current_user
      redirect_to root_path, info: "User account and all associated articles were deleted"
  end

  private
  def user_params
      params.require(:user).permit(:username, :email, :password)
  end
  def set_user
      @user = User.find(params[:id])
  end
  def require_same_user
      if current_user != @user && !current_user.admin?
          redirect_to @user, danger: "You can only update your own profile"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header three">
<i class="circular orange comments outline icon"></i>
  Say Something
</h4>
<div class="ui stackable doubling two column grid">

    <div  class="four wide column ">
        <div id="rightColumn" class="ui fluid raised card">
            <div class="content three">
                <div  class="ui inverted vertical menu menu1">
                    <a class="item three">
                        Home
                    </a>
                    <a class="item three">
                        Messages
                    </a>
                    <a class="item three">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div id="messages" class="content">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
                    <div class="field">
                        <div class="ui fluid icon input">
                            <%= f.text_field :body %>
                            <%= f.button '<i class="bordered inverted orange icon edit"></i>'.html_safe %>
                        </div>                    
                    </div>
                <% end %>
            </div>
        </div>
        
    </div>
    

</div>

app/views/layouts/_flashmessages.html.erb
<div class="ui container mb-4">
<center>
<% flash.each do |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition ">
      <i class="close icon"></i>
      <div class="header">
        <h1><%= message_content %></h1>
      </div>
    </div>
  <% end %>
  </center>

  </div>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
    <div class="ui container">
        <a class="item" href="/">
            Chatroom
        </a>
        <a class="item">
            Messages
        </a>
        <div class="right menu">
        <% if !logged_in? %>
            <div class="item">

                
                <%= link_to "Sign Up", signup_path, class: "ui primary button" %>
               
            </div>
            <% else %>
            <div class="item">
            <div class="ui primary">Signed in as: <%= current_user.username %>
            </div>
            </div>
            <% end %>
            <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
            <% if logged_in? %>
                <%= link_to "Log out", logout_path, class: "item", method: :delete %>
            <% else %>
                <a class="item" href="login">Log in / Sign up</a>
                
            <% end %>
            </div>
            </div>
            
        </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/flashmessages' %>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="card1" class="ui raised card">
  <div class="content">
    <div class="header"><em class="three"><%=  message.user.username %></em></div>
    <div class="meta">
    </div>
    <div class="description three">
      <p><%= message.body %></p>
    </div>
  </div>
  
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, class: "ui inverted form") do |f| %>
    <div class="two fields">
        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username, placeholder: "User Name" %>
        </div>
        <div class="field"> 
            <%= f.label :password %>
            <%= f.password_field :password, placeholder: "Password" %>
        </div>
    </div>
    <div class="field">
        <%= f.label :email%>
        <%= f.email_field :email, placeholder: "Email Address" %>
    </div>
       
    <div class="actions">
      <%= f.submit "Sign up", class: "ui submit button" %>
    </div>
  <% end %>




  <div class="ui orange big button" data-modal-target="signup" onclick="ShowModal()">

app/views/users/new.html.erb
<div class="mt-25">

<div class="ui  inverted segment">

<%= form_with(model: @user, local: true, class: "ui inverted form") do |f| %>
  
        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username, placeholder: "User Name" %>
        </div><br>
        <div class="field"> 
            <%= f.label :password %>
            <%= f.password_field :password, placeholder: "Password" %>
        </div><br>
    
    <div class="field">
        <%= f.label :email%>
        <%= f.email_field :email, placeholder: "Email Address" %>
  
      </div><br> 
    <div class="actions">
      <%= f.submit "Sign up", class: "ui inverted brown button big fluid" %>
    </div><br>
    <div class="actions">
      <%= link_to "Returning user! - Log in", login_path, class: "ui inverted brown button big fluid" %>
    </div>
  <% end %>
</div>
</div>